---
# macOS-specific system tweaks and maintenance

- name: Disable automatic app updates
  ansible.builtin.command: defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true
  when: ansible_os_family == "Darwin"
  changed_when: false
  check_mode: true
  tags: [mac, updates]

- name: Set screenshot save location to Downloads
  ansible.builtin.command: defaults write com.apple.screencapture location ~/Downloads
  when: ansible_os_family == "Darwin"
  changed_when: false
  check_mode: true
  tags: [mac, screenshots]

- name: Set US keyboard layout as default
  ansible.builtin.command: defaults write com.apple.HIToolbox AppleCurrentKeyboardLayoutInputSourceID -string "com.apple.keylayout.US"
  when: ansible_os_family == "Darwin"
  changed_when: false
  check_mode: true
  tags: [mac, keyboard]
