- name: Cleanup Brew packages
  when: ansible_os_family == "Darwin"
  command: brew cleanup

- name: 'Save screenshots to Downloads'
  when: ansible_os_family == "Darwin"
  shell: defaults write com.apple.screencapture location ~/Downloads
