---
# macOS-specific system tweaks and maintenance

- name: Disable automatic app updates
  ansible.builtin.command: defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true
  when: ansible_os_family == "Darwin"
  tags: [updates]

- name: Set screenshot save location to Downloads
  ansible.builtin.command: defaults write com.apple.screencapture location ~/Downloads
  when: ansible_os_family == "Darwin"
  tags: [screenshots]

- name: Set US keyboard layout as default
  ansible.builtin.command: defaults write com.apple.HIToolbox AppleCurrentKeyboardLayoutInputSourceID -string "com.apple.keylayout.US"
  when: ansible_os_family == "Darwin"
  tags: [keyboard]

- name: Install kube tools
  when:
    - ansible_env.HOME is defined
  ansible.builtin.import_tasks: kube.yml
  tags: devops
