---
- name: Cleanup Brew packages
  when: ansible_os_family == "Darwin"
  ansible.builtin.command: brew cleanup
- name: Save screenshots to Downloads
  when: ansible_os_family == "Darwin"
  ansible.builtin.command: defaults write com.apple.screencapture location ~/Downloads
