---
# macOS-specific system tweaks and maintenance
- name: Cleanup Homebrew packages
  ansible.builtin.command: brew cleanup
  when: ansible_os_family == "Darwin"
  tags: [brew, cleanup]

- name: Set screenshot save location to Downloads
  ansible.builtin.command: defaults write com.apple.screencapture location ~/Downloads
  when: ansible_os_family == "Darwin"
  tags: [screenshots]

- name: Set US keyboard layout as default
  ansible.builtin.command: defaults write com.apple.HIToolbox AppleCurrentKeyboardLayoutInputSourceID -string "com.apple.keylayout.US"
  when: ansible_os_family == "Darwin"
  tags: [keyboard]

- name: Installing FZF
  when: 
    - ansible_os_family == "Darwin"
  block:
    - name: Install fzf on Darwin
      community.general.homebrew:
        name: fzf
        state: present
      tags: [fzf]
    - name: fzf key bindings and fuzzy completion
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh"
        insertafter: EOF
