#!/bin/bash
set -e
set -u
# Define color codes
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
# Function to log info messages
log_info() {
    echo -e "${GREEN}$1${NC}"
}

# Function to log error messages
log_error() {
    echo -e "${RED}$1${NC}"
}

# Function to log warning messages
log_warning() {
    echo -e "${YELLOW}$1${NC}"
}
# Install dependencies based on OS
os_family=$(uname)
if [ "$os_family" == "Linux" ]; then
# shellcheck disable=SC1091
  os_family=$(source /etc/os-release && echo "$ID")
  log_warning "OS is: $os_family"
elif [ -z "$os_family" ]; then
  log_error "Unable to identify OS"
  exit 1
fi

declare -r playbook_file="${os_family}.yml"
if ! tty -s; then
  log_warning "Script is running in unattended mode."
  ansible-playbook -i inventory "$playbook_file"
else
  log "Script is running in attended mode."
  ansible-playbook -i inventory "$playbook_file" -K
fi
