#!/bin/bash
set -e
set -u

# shellcheck disable=SC1091
source "$DOTFILES_DIR/lib/log.sh"
# shellcheck disable=SC1091
source "$DOTFILES_DIR/lib/utils.sh"
declare -r DOTFILES_DIR="${DOTFILES_DIR:-}"
declare -r os_family_override="${OS_FAMILY_OVERRIDE:-}"
declare -r playbook_file="${os_family_override:-${os_family}}.yml"
declare -r REMOTE_USER="${REMOTE_USER:-}"

if [[ -n "$os_family_override" ]]; then
  log_info "Using OS family: $os_family with override"
  ansible-playbook -K -i inventory "$playbook_file"
elif ! tty -s; then
  log_warning "Script is running in unattended mode."
  export ANSIBLE_STDOUT_CALLBACK=minimal
  export ANSIBLE_NO_WARNINGS=True
  ansible-playbook -i inventory "$playbook_file" -u "${SUDO_USER:-$USER}" -b
else
  log_info "Script is running in attended mode."
  ansible-playbook -i inventory "$playbook_file" -u "$REMOTE_USER" -b -K "$@" -vvv
fi
