---
- name: Setting up mac environment
  hosts: local
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check
    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
  roles:
    - role: osx
    - role: common
  tasks:
    # ensure sops key is loaded and placed
    # install 1password
    # Personal
    # signal, whatsapp, facebook messenger
    # install vscode
    # install iterm2
    # install powercalc10 for iterm2
    # install kubectl
    # install sops
    # ansible-lint
# - name: Install cask
#   community.general.homebrew_cask:
#     name: "{{ item }}"
#     state: present
#     with_items:
#       - google-drive
#       - instaloader
#       - tradingview
      # - caskformula/caskformula/inkscape # fails
    # brew install fluxcd/tap/flux and . <(flux completion zsh)
    # git config --global core.excludesFile "~/.gitignore_global"
    # brew install --cask whisky
