---
- name: Setup macOS
  hosts: laptop
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Exit if not running on macOS
      ansible.builtin.fail:
        msg: "This playbook is intended for macOS only."
      when: ansible_facts['os_family'] != "Darwin"
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

  tasks:
    - name: Install cask apps
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        - 1password-cli
        - google-drive
        - instaloader
        - tradingview
        - autodesk-fusion
        - drawio
        - orcaslicer
        - bambu-studio
        - dropbox
        - firefox
        - visual-studio-code
        - discord
        - vivaldi
        - dozer
        - iterm2
